version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ifrs
      POSTGRES_PASSWORD: ifrs
      POSTGRES_DB: ifrsdb
    ports:
      - "51432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
